/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from 'kysely';

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>;

export type NotificationDelivery = 'both' | 'email' | 'inapp' | 'none';

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Permissions {
  global: Generated<boolean>;
  key: string;
  order: Generated<number>;
  parent_permission_key: string | null;
}

export interface RefreshTokens {
  expires_at: Timestamp;
  id: string;
  user_id: number;
}

export interface Roles {
  deleted_at: Timestamp | null;
  description: string;
  id: Generated<number>;
  slug: string;
}

export interface RolesPermissions {
  permission_key: string;
  role_id: number;
}

export interface Settings {
  key: string;
  updated_at: Generated<Timestamp>;
  value: string;
}

export interface Sites {
  deleted_at: Timestamp | null;
  id: Generated<number>;
  name: string;
}

export interface Skills {
  deleted_at: Timestamp | null;
  id: Generated<number>;
  name: string;
}

export interface Users {
  activity_end_delivery: NotificationDelivery;
  activity_expiration_delivery: NotificationDelivery;
  activity_start_delivery: NotificationDelivery;
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  email: string;
  first_name: string;
  id: Generated<number>;
  last_name: string;
  nickname: string;
  nomination_end_delivery: NotificationDelivery;
  nomination_expiration_delivery: NotificationDelivery;
  nomination_start_delivery: NotificationDelivery;
  password: string;
  phone_number: string | null;
  security_end_delivery: NotificationDelivery;
  security_expiration_delivery: NotificationDelivery;
  security_start_delivery: NotificationDelivery;
  training_end_delivery: NotificationDelivery;
  training_expiration_delivery: NotificationDelivery;
  training_start_delivery: NotificationDelivery;
  updated_at: Timestamp | null;
}

export interface UsersPermissions {
  permission_key: string;
  user_id: number;
}

export interface UsersRoles {
  role_id: number;
  user_id: number;
}

export interface DB {
  permissions: Permissions;
  refresh_tokens: RefreshTokens;
  roles: Roles;
  roles_permissions: RolesPermissions;
  settings: Settings;
  sites: Sites;
  skills: Skills;
  users: Users;
  users_permissions: UsersPermissions;
  users_roles: UsersRoles;
}
