/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from 'kysely';

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>;

export type NotificationDelivery = 'both' | 'email' | 'inapp' | 'none';

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Permissions {
  global: Generated<boolean>;
  key: string;
  order: Generated<number>;
  parentPermissionKey: string | null;
}

export interface RefreshTokens {
  expiresAt: Timestamp;
  id: string;
  userId: number;
}

export interface Roles {
  deletedAt: Timestamp | null;
  description: string;
  id: Generated<number>;
  slug: string;
}

export interface RolesPermissions {
  permissionKey: string;
  roleId: number;
}

export interface Settings {
  key: string;
  updatedAt: Generated<Timestamp>;
  value: string;
}

export interface Sites {
  deletedAt: Timestamp | null;
  id: Generated<number>;
  name: string;
}

export interface Skills {
  deletedAt: Timestamp | null;
  id: Generated<number>;
  name: string;
}

export interface Users {
  activityEndDelivery: NotificationDelivery;
  activityExpirationDelivery: NotificationDelivery;
  activityStartDelivery: NotificationDelivery;
  createdAt: Generated<Timestamp>;
  deletedAt: Timestamp | null;
  email: string;
  firstName: string;
  id: Generated<number>;
  lastName: string;
  nickname: string;
  nominationEndDelivery: NotificationDelivery;
  nominationExpirationDelivery: NotificationDelivery;
  nominationStartDelivery: NotificationDelivery;
  password: string;
  phoneNumber: string | null;
  securityEndDelivery: NotificationDelivery;
  securityExpirationDelivery: NotificationDelivery;
  securityStartDelivery: NotificationDelivery;
  trainingEndDelivery: NotificationDelivery;
  trainingExpirationDelivery: NotificationDelivery;
  trainingStartDelivery: NotificationDelivery;
  updatedAt: Timestamp | null;
}

export interface UsersPermissions {
  permissionKey: string;
  userId: number;
}

export interface UsersRoles {
  roleId: number;
  userId: number;
}

export interface DB {
  permissions: Permissions;
  refreshTokens: RefreshTokens;
  roles: Roles;
  rolesPermissions: RolesPermissions;
  settings: Settings;
  sites: Sites;
  skills: Skills;
  users: Users;
  usersPermissions: UsersPermissions;
  usersRoles: UsersRoles;
}
